In [50]:
import pandas as pd
import numpy as np

In [51]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.pipeline import Pipeline, make_pipeline

In [52]:
df = pd.read_csv('Titanic_Dataset.csv')

In [53]:
df.head(4)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [54]:
df.drop(columns=['PassengerId', 'Name',  'Ticket','Cabin'], inplace = True)

In [55]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['Survived']), df['Survived'], test_size=0.2, random_state=42)

In [56]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((712, 7), (179, 7), (712,), (179,))

In [57]:
type(X_train), type(X_test), y_train.dtype, y_test.dtype

(pandas.core.frame.DataFrame,
 pandas.core.frame.DataFrame,
 dtype('int64'),
 dtype('int64'))

In [58]:
X_train.head(4)

     Pclass   Sex   Age  SibSp  Parch     Fare Embarked
331       1  male  45.5      0      0  28.5000        S
733       2  male  23.0      0      0  13.0000        S
382       3  male  32.0      0      0   7.9250        S
704       3  male  26.0      1      0   7.8542        S

In [59]:
X_train.isnull().sum()

Pclass        0
Sex           0
Age         140
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [60]:
y_train

331    0
733    0
382    0
704    0
813    0
      ..
106    1
270    0
860    0
435    1
102    0
Name: Survived, Length: 712, dtype: int64

In [61]:
y_train.dtype, type(X_train )

(dtype('int64'), pandas.core.frame.DataFrame)

In [71]:
transformer1 = ColumnTransformer([
    ('impute_age', SimpleImputer(), [2]),
    ('impute_embarked', SimpleImputer(strategy="most_frequent"), [6] )
    ], remainder='passthrough'
)

In [80]:
transformer2 = ColumnTransformer(
[
 ('ohe', OneHotEncoder(sparse_output=False, handle_unknown='ignore'),
  ['Sex','Embarked'])
],
remainder='passthrough'
)

In [81]:
transformer3 = ColumnTransformer(
    [
        ('scale', MinMaxScaler(),slice(0,10) )
    ], remainder = 'passthrough'
)

In [82]:
transformer4 = SelectKBest(score_func=chi2, k =8)

In [83]:
transformer5 = DecisionTreeClassifier()

In [84]:
X_train.shape, y_train.shape

((712, 7), (712,))

<h1> Use Pipelines </h1>

<p> difference between pipeline and make_pipeline is that we need to pass every single step in pipeline and in make_pipeline () we just pass the names directly

In [85]:
pipe = make_pipeline(transformer1, transformer2, transformer3, transformer4, transformer5)

In [87]:
pipe.fit(X_train, y_train)

ValueError: Specifying the columns using strings is only supported for dataframes.