In [2]:
import pandas as pd 
import numpy as np

In [3]:
df = pd.read_csv("covid_data.csv")

In [4]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [12]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [10]:
df.describe()

              age       fever
count  100.000000   90.000000
mean    44.220000  100.844444
std     24.878931    2.054926
min      5.000000   98.000000
25%     20.000000   99.000000
50%     45.000000  101.000000
75%     66.500000  102.750000
max     84.000000  104.000000

<h3> Column transformer traditionally </h3>
<p> here columns are to be tranformed separately and then the data is merged to get all columns </p>

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
X_train, X_test, y_train, y_test = train_test_split(df.drop('has_covid', axis=1),df['has_covid'], test_size=0.2, random_state=0)

<p> using SimpleImputer it will fill up the spaces where the data has blank value in means, here age col is not categorical so we'll impute with average values</p>

In [15]:
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])
X_train_fever.shape

(80, 1)

In [19]:
X_test_fever = si.fit_transform(X_test[['fever']])

In [16]:
df['city'].unique()

array(['Kolkata', 'Delhi', 'Mumbai', 'Bangalore'], dtype=object)

In [17]:
df['cough'].unique()

array(['Mild', 'Strong'], dtype=object)

In [18]:
df['gender'].unique()

array(['Male', 'Female'], dtype=object)

In [ ]:
# here we have ordinal categories are: cough and label encoding = covid applied on output col
# and nominal data : City, Gender

<p> One Hot Encoding on City and Gender Col <p>

In [20]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder

In [24]:
ohe = OneHotEncoder(drop='first')
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)

In [ ]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [ ]:
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [29]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed.shape

NameError: name 'X_train_cough' is not defined