In [6]:
import numpy as np 
import pandas as pd

In [33]:
df = pd.read_csv("customer.csv")

In [34]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [ ]:
df = df.iloc[:, -3:]

# or we can use [:,2:]

In [36]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import  OrdinalEncoder,LabelEncoder
# ordinal encoder is for input columns that are two cols in starting 
# label encoder is for output col that is purchased

In [37]:
X_train, X_test, y_train, y_test = train_test_split(df.drop('purchased', axis=1), df['purchased'], test_size=0.2, random_state=0)

In [39]:
X_train.head()

     review education
33     Good        PG
35     Poor    School
26     Poor        PG
34  Average    School
18     Good    School